//
//  StoriesView.swift
//  VoicesAI
//
//  Created by User50 on 24/04/24.
//

import SwiftUI

struct StoriesView: View {
    @State private var selectedTopics: Topics = .persahabatan
    @State private var selectedMood: Mood = .bahagia
    @State private var todayStory: String = ""
    
    var body: some View {
        NavigationStack{
            Form {
                
                Section {
                    Picker("Choose Topics", selection: $selectedTopics) {
                        ForEach(Topics.allCases,id: \.self) {topic  in
                            Text(topic.rawValue.capitalized)
                                .font(.subheadline)
                                .tag(topic)
                        }
                    }
                    .foregroundStyle(.gray)
                    
                    Picker(selection: $selectedMood) {
                        ForEach(Mood.allCases,id: \.self) {mood  in
                            Text(mood.rawValue.capitalized)
                                .font(.subheadline)
                                .tag(mood)
                        }
                        
                    }label: {
                        Text("Choose topics")
                            .foregroundStyle(.gray)
                    }
                } header: {
                    Text("Topics")
                } footer: {
                    Text("Choose any topics and mood that you want to listen")
                }
                
                // MARK: -
                Section {
                    TextEditor(text: $todayStory)
                        .frame(height: 200)
                        .foregroundStyle(.blue)
                } header: {
                    Text("Todays Story")
                } footer: {
                    Text("This stories are being generated by Gemini AI.")
                }
                
                // MARK: - BUTTON GENERATE
                Button {
                    // Todo
                    
                } label: {
                    Text("Generate".uppercased())
                        .font(.system(.callout, design: .rounded))
                        .fontWeight(.bold)
                }
                .buttonStyle(.plain)
                .frame(minWidth: 0,maxWidth: .infinity)
            }
            .navigationTitle("Stories")
//            .navigationBarTitleDisplayMode(.inline)
            .tint(.black)
            
        }
    }
}

#Preview {
    StoriesView()
}
